### ISSUE TITLE
Feature request: Tip jar

### ISSUE THREAD

**Issue by d4rky-pl** [jiripospisil/idea-gototabs#6]
Considering this plugin saved me *a lot* of time, I would really love to give some of that time back in form of a small tip :)

Please consider opening a (PayPal?) tip jar!

**Comment by jiripospisil** [comment]
I'm glad to hear that! :) As far as donations go, there's no need for that. If you want, you can donate the amount to a charity of your choice (e.g. [Make-A-Wish](https://worldwish.org/en/donate) or [charity: water](https://www.charitywater.org/donate)).
